#!/bin/sh

set -e

if [ -z "$TIMEOUT" ] ; then
  TIMEOUT=300
fi

git submodule update --recursive --init

git clone git@github.com:healthcareapp-ufmg/tls-data.git
cd tls-data
make domain-server-decrypt-with-password OUTPUT_DIR="$HOME/docker/certs.d"
cd ..

docker run --rm --name docker-deployment \
  -e DOCKER_SERVER_IP=$DOCKER_REMOTE_IP \
  -e DOCKER_COMPOSE_FILE=/opt/docker-compose.yml \
  -e DOCKER_REGISTRY_HOST="localhost:5000" \
  -e DOCKER_REGISTRY_PASSWORD=$DOCKER_REGISTRY_PASSWORD \
  -e DOCKER_REGISTRY_USERNAME=$DOCKER_REGISTRY_USERNAME \
  -e TIMEOUT=$TIMEOUT \
  -e FORCE=true \
  -v $HOME/docker/certs.d:/etc/docker/certs.d \
  -v ./cd/docker-compose.yml:/opt/docker-compose.yml \
  eliasmeireles/docker-deployment:v1
