services:
  proxy-server:
    container_name: proxy-server-example
    image: nginx:latest
    ports:
      - "8575:80"
    #    volumes:
    #      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
  http-request:
    container_name: http-request-example
    image: eliasmeireles/http-request
    depends_on:
      - proxy-server
    ports:
      - "8693:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
