#!/bin/bash

sudo apt-get update && sudo apt-get install -y \
    apt-transport-https \
    make \
    ca-certificates \
    curl \
    net-tools

curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

# Setup Docker CLI plugins directory
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
sudo mkdir -p "$DOCKER_CONFIG"/cli-plugins

# Download and install Docker Compose
sudo curl -SL "https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-$(uname -s)-$(uname -m)" -o "$DOCKER_CONFIG"/cli-plugins/docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Clean up
sudo rm -rf /home/ubuntu/docker
